export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const CHANGE_IMAGE = 'CHANGE_IMAGE';
export const CHANGE_PROFILE = 'CHANGE_PROFILE';
export const LOAD_STATUS_MESSAGE = 'LOAD_STATUS_MESSAGE';
export const LOAD_STATUS_NAME = 'LOAD_STATUS_NAME';
export const LOAD_FRIENDS_LIST = 'LOAD_FRIENDS_LIST';
export const LOAD_ALL_FRIENDS_LIST = 'LOAD_ALL_FRIENDS_LIST';
export const LOAD_ALARM_STATUS = 'LOAD_ALARM_STATUS';

export const SET_CURRENT_CHAT_FRIEND = 'SET_CURRENT_CHAT_FRIEND';
